name: Update README

on:
  schedule:
    - cron: '*/3 * * * *' # Run every 3 minutes
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README with current status
